### ISSUE TITLE
CPM doesn't open on Android 14 (with Xposed method), works with Accessibility method still

### ISSUE THREAD

**Issue by i5lee8bit** [KieronQuinn/ClassicPowerMenu#123]
Just updated my Pixel 7 Pro to A14, factory ROM. CPM no longer opens, UNLESS THE APP IS ACTIVELY RUNNING. In that case, having only the Xposed module running works fine. As soon as I swipe CPM away from recents, holding power button does nothing. Just a little haptic feedback you'd expect but nothing shows up.

For now, I just enabled accessibility service and it works fine again. I guess just the Xposed module needs updating.

CPM 1.7.0
Magisk 26.3
LSposed 1.9.1
(edit, and yes I have CPM unrestricted from battery optimization)

Thanks for this wonderful project, been using it happily for quite a while now!! Let me know if you want any more info or want me to capture any logs or anything.

**Comment by bggold** [comment]
Same thing for me.  Also a great app.

**Comment by KieronQuinn** [comment]
I've managed to track this down finally, it's due to background start restrictions introduced on Android 14. 

You can work around it by running 

`cmd device_config put activity_manager default_background_activity_starts_enabled true`

in a root shell, or you can wait until an update where I'll have to switch it so the activity is started by root.

**Comment by KieronQuinn** [comment]
Fixed in 1.7.1

Run the same command as above but with "false" instead of "true" to revert it after updating.
